
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.schemas.client;

import gov.samhsa.ds4ppilot.contract.orchestrator.XDSDocumentServicePortType;
import gov.samhsa.ds4ppilot.schema.orchestrator.SaveDocumentSetToXdsRepositoryResponse;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-07-10T23:02:36.561-04:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "XDSDocumentService",
                      portName = "XDSDocumentServicePort",
                      targetNamespace = "http://www.samhsa.gov/ds4ppilot/contract/orchestrator",
                      wsdlLocation = "classpath:XdsDocumentService.wsdl",
                      endpointInterface = "gov.samhsa.ds4ppilot.contract.orchestrator.XDSDocumentServicePortType")
                      
public class XDSDocumentServicePortTypeImpl implements XDSDocumentServicePortType {

    private static final Logger LOG = Logger.getLogger(XDSDocumentServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see gov.samhsa.ds4ppilot.contract.orchestrator.XDSDocumentServicePortType#saveDocumentSetToXdsRepository(gov.samhsa.ds4ppilot.schema.orchestrator.SaveDocumentSetToXdsRepositoryRequest  parameters )*
     */
    public gov.samhsa.ds4ppilot.schema.orchestrator.SaveDocumentSetToXdsRepositoryResponse saveDocumentSetToXdsRepository(gov.samhsa.ds4ppilot.schema.orchestrator.SaveDocumentSetToXdsRepositoryRequest parameters) { 
        LOG.info("Executing operation saveDocumentSetToXdsRepository");
        System.out.println(parameters);
        try {
            gov.samhsa.ds4ppilot.schema.orchestrator.SaveDocumentSetToXdsRepositoryResponse _return = returnedValueOfSaveDocumentSetToXdsRepository;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    public static SaveDocumentSetToXdsRepositoryResponse returnedValueOfSaveDocumentSetToXdsRepository = null;

}
