-- MySQL Script generated by MySQL Workbench
-- 03/17/15 11:30:48
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema polrep
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `polrep` ;
CREATE SCHEMA IF NOT EXISTS `polrep` DEFAULT CHARACTER SET utf8 ;
USE `polrep` ;

-- -----------------------------------------------------
-- Table `policies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policies` (
  `id` VARCHAR(255) NOT NULL,
  `policy` LONGBLOB NULL DEFAULT NULL,
  `valid` BIT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `revinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revinfo` (
  `REV` INT(11) NOT NULL AUTO_INCREMENT,
  `REVTSTMP` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`REV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `policies_aud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policies_aud` (
  `id` VARCHAR(255) NOT NULL,
  `REV` INT(11) NOT NULL,
  `REVTYPE` TINYINT(4) NULL DEFAULT NULL,
  `policy` LONGBLOB NULL DEFAULT NULL,
  `valid` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  INDEX `FK_mr908cu0o97xfy8r02igbo6le` (`REV` ASC),
  CONSTRAINT `FK_mr908cu0o97xfy8r02igbo6le`
    FOREIGN KEY (`REV`)
    REFERENCES `revinfo` (`REV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
