
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.acs.pep.wsclient;

import gov.samhsa.ds4ppilot.contract.pep.PepPortType;
import gov.samhsa.ds4ppilot.schema.pep.DirectEmailSendResponse;
import ihe.iti.xds_b._2007.RetrieveDocumentSetResponse;

import java.util.logging.Logger;

import oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse;
import oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponseType;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-04-03T13:57:58.899-04:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "PepService",
                      portName = "XDS_HTTP_Endpoint",
                      targetNamespace = "http://www.samhsa.gov/ds4ppilot/contract/pep",
                      wsdlLocation = "classpath:Pep.wsdl",
                      endpointInterface = "gov.samhsa.ds4ppilot.contract.pep.PepPortType")
                      
public class PepPortTypeImpl implements PepPortType {

    private static final Logger LOG = Logger.getLogger(PepPortTypeImpl.class.getName());
    
    public static oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse returnedValueOfPep = new AdhocQueryResponse();

    /* (non-Javadoc)
     * @see gov.samhsa.ds4ppilot.contract.pep.PepPortType#registryStoredQuery(oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryRequest  input )*
     */
    public oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse registryStoredQuery(oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryRequest input) { 
        LOG.info("Executing operation registryStoredQuery");
        System.out.println(input);
        try {
        	returnedValueOfPep.setRequestId("testId");
            oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryResponse _return = returnedValueOfPep;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.samhsa.ds4ppilot.contract.pep.PepPortType#directEmailSend(gov.samhsa.ds4ppilot.schema.pep.DirectEmailSendRequest  parameters )*
     */
    public gov.samhsa.ds4ppilot.schema.pep.DirectEmailSendResponse directEmailSend(gov.samhsa.ds4ppilot.schema.pep.DirectEmailSendRequest parameters) { 
        LOG.info("Executing operation directEmailSend");
        System.out.println(parameters);
        try {
            gov.samhsa.ds4ppilot.schema.pep.DirectEmailSendResponse _return = new DirectEmailSendResponse();
            _return.setPatientId("testId");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.samhsa.ds4ppilot.contract.pep.PepPortType#retrieveDocumentSet(ihe.iti.xds_b._2007.RetrieveDocumentSetRequest  input )*
     */
    public ihe.iti.xds_b._2007.RetrieveDocumentSetResponse retrieveDocumentSet(ihe.iti.xds_b._2007.RetrieveDocumentSetRequest input) { 
        LOG.info("Executing operation retrieveDocumentSet");
        System.out.println(input);
        try {
            ihe.iti.xds_b._2007.RetrieveDocumentSetResponse _return = new RetrieveDocumentSetResponse();
            RegistryResponseType registryResponseType = new RegistryResponseType();
            registryResponseType.setRequestId("testId");
            _return.setRegistryResponse(registryResponseType);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
