/*******************************************************************************
 * Open Behavioral Health Information Technology Architecture (OBHITA.org)
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the <organization> nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 11:05:26 AM EDT 
//


package gov.samhsa.consent2share.c32.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


// TODO: Auto-generated Javadoc
/**
 * Reusable organization information
 * 
 * <p>Java class for organizationInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organizationInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="organizationID" type="{urn:hl7-org:v3}ii" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="organizationAddress" type="{urn:hl7-org:v3}addr" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="organizationTelecom" type="{urn:hl7-org:v3}tele" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="organizationName" type="{urn:hl7-org:v3}onm" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organizationInformation", propOrder = {
    "organizationID",
    "organizationAddress",
    "organizationTelecom",
    "organizationName"
})
public class OrganizationInformation {

    /** The organization id. */
    protected List<Ii> organizationID;
    
    /** The organization address. */
    protected List<Addr> organizationAddress;
    
    /** The organization telecom. */
    protected List<Tele> organizationTelecom;
    
    /** The organization name. */
    protected Onm organizationName;

    /**
     * Gets the value of the organizationID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getOrganizationID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     *
     * @return the organization id
     * {@link Ii }
     */
    public List<Ii> getOrganizationID() {
        if (organizationID == null) {
            organizationID = new ArrayList<Ii>();
        }
        return this.organizationID;
    }

    /**
     * Gets the value of the organizationAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getOrganizationAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     *
     * @return the organization address
     * {@link Addr }
     */
    public List<Addr> getOrganizationAddress() {
        if (organizationAddress == null) {
            organizationAddress = new ArrayList<Addr>();
        }
        return this.organizationAddress;
    }

    /**
     * Gets the value of the organizationTelecom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationTelecom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getOrganizationTelecom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     *
     * @return the organization telecom
     * {@link Tele }
     */
    public List<Tele> getOrganizationTelecom() {
        if (organizationTelecom == null) {
            organizationTelecom = new ArrayList<Tele>();
        }
        return this.organizationTelecom;
    }

    /**
     * Gets the value of the organizationName property.
     *
     * @return the organization name
     * possible object is
     * {@link Onm }
     */
    public Onm getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Onm }
     *     
     */
    public void setOrganizationName(Onm value) {
        this.organizationName = value;
    }

}
