/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.schemas.client;

import gov.samhsa.ds4ppilot.contract.documentprocessor.ProcessDocumentServicePortType;
import gov.samhsa.ds4ppilot.schema.documentprocessor.ProcessDocumentResponse;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-09-24T09:56:01.131-04:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProcessDocumentService",
                      portName = "ProcessDocumentPort",
                      targetNamespace = "http://www.samhsa.gov/ds4ppilot/contract/documentprocessor",
                      wsdlLocation = "classpath:DocumentProcessor.wsdl",
                      endpointInterface = "gov.samhsa.ds4ppilot.contract.documentprocessor.ProcessDocumentServicePortType")
                      
public class IDocumentProcessorImpl implements ProcessDocumentServicePortType {

	public static ProcessDocumentResponse returnedValueOfProcessDocument;
    private static final Logger LOG = Logger.getLogger(IDocumentProcessorImpl.class.getName());

    /* (non-Javadoc)
     * @see gov.samhsa.ds4ppilot.contract.documentprocessor.ProcessDocumentServicePortType#processDocument(gov.samhsa.ds4ppilot.schema.documentprocessor.ProcessDocumentRequest  parameters )*
     */
    @Override
	public gov.samhsa.ds4ppilot.schema.documentprocessor.ProcessDocumentResponse processDocument(gov.samhsa.ds4ppilot.schema.documentprocessor.ProcessDocumentRequest parameters) { 
        LOG.info("Executing operation processDocument");
        System.out.println(parameters);
        try {
            gov.samhsa.ds4ppilot.schema.documentprocessor.ProcessDocumentResponse _return = returnedValueOfProcessDocument;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
